### ISSUE TITLE
Plugin file JAVA 

### ISSUE THREAD

**Issue by RebelLP** [PlayFriik/Annihilation#3]
Hello, I would like if you could give me your plugin Annihilation in JAVA file somehow I can not thank you.

**Comment by PlayFriik** [comment]
https://github.com/PlayFriik/Annihilation/archive/master.zip

**Comment by RebelLP** [comment]
please give me the Java plug-in file

**Comment by PlayFriik** [comment]
https://github.com/PlayFriik/Annihilation/releases/download/v1.5.1/Annihilation-1.5.1.jar

**Comment by RebelLP** [comment]
fenkju

**Comment by PlayFriik** [comment]
No problem.

**Comment by RebelLP** [comment]
Could you please fix the bug with the portal? and add some kits?

**Comment by RebelLP** [comment]
[22:17:17] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Annihilation v1.5.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Bukkit-d27e6d0]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Bukkit-d27e6d0]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [spigot.jar:git-Bukkit-d27e6d0]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [spigot.jar:git-Bukkit-d27e6d0]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:210) [spigot.jar:git-Bukkit-d27e6d0]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:177) [spigot.jar:git-Bukkit-d27e6d0]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:173) [spigot.jar:git-Bukkit-d27e6d0]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:688) [spigot.jar:git-Bukkit-d27e6d0]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot.jar:git-Bukkit-d27e6d0]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot.jar:git-Bukkit-d27e6d0]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Bukkit-d27e6d0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-Bukkit-d27e6d0]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:672) [spigot.jar:git-Bukkit-d27e6d0]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [spigot.jar:git-Bukkit-d27e6d0]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628) [spigot.jar:git-Bukkit-d27e6d0]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536) [spigot.jar:git-Bukkit-d27e6d0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.IllegalStateException: Start block missed in BlockIterator
	at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:170) ~[spigot.jar:git-Bukkit-d27e6d0]
	at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:233) ~[spigot.jar:git-Bukkit-d27e6d0]
	at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:268) ~[spigot.jar:git-Bukkit-d27e6d0]
	at net.PlayFriik.Annihilation.listeners.WandListener.getTargetEntity(WandListener.java:89) ~[?:?]
	at net.PlayFriik.Annihilation.listeners.WandListener.onWandUse(WandListener.java:66) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[spigot.jar:git-Bukkit-d27e6d0]
	... 18 more


PS:Pls fix

**Comment by RebelLP** [comment]
and please can you have sent t the files that you imported into eclips (Bukkit, vault)

**Comment by RebelLP** [comment]
Dobry den,toto jsem už zkoušel ale piše mit of urt chybu podle mně to bude něco v tom budu rad jesli by bylo možne m poslat váš workspace

**Comment by PlayFriik** [comment]
Firstly - don't post errors here. Paste them, for example, there: pastebin.com
Secondly - make sure that your server is 1.8.7 Bukkit/Spigot.
Thirdly - I used latest Bukkit AND CraftBukkit, Vault was also latest. You can find different Bukkit/CraftBukkit/Spigot builds from tcpr.ca.

**Comment by PlayFriik** [comment]
Fourthly - I said already to one guy that I am just updating the plugin.

**Comment by RebelLP** [comment]
nilly would you have me do for java devlopera more for my project ye would have us modify Anni plugin would have added that much kit etc.?

**Comment by PlayFriik** [comment]
Sorry, I don't understand you.

**Comment by RebelLP** [comment]
oh ok. :( You would not want me to customize the Plugin Anni so there was not even 1 bug? And would you have added suitably kit

**Comment by PlayFriik** [comment]
Well, I said already that I am just updating the plugin, not adding kits. I don't want to waste my time on free plugins, because paid plugins are more important to me.

**Comment by RebelLP** [comment]
I understand I will not please us to adjust at least one bug with portalama nemuiste that giving even on github Just when we send u JAVA file

**Comment by PlayFriik** [comment]
portalama nemuiste? What?
And I don't want Java file. I already have it...

**Comment by RebelLP** [comment]
I'd like if you fix a bug with portals

**Comment by PlayFriik** [comment]
What portals? Class changing portals?

**Comment by RebelLP** [comment]
Wait a minute I send you a video

**Comment by PlayFriik** [comment]
Okay

**Comment by RebelLP** [comment]
https://www.youtube.com/watch?v=PBtPKEqRd5c&feature=youtu.be

**Comment by PlayFriik** [comment]
This video is private.

**Comment by RebelLP** [comment]
ok

**Comment by PlayFriik** [comment]
Umm what's wrong with that?

**Comment by RebelLP** [comment]
when he climbs into the portal and kill him! how soon climbs into the portal so it's ma portnout his spawn and when choosing a kit after it killed te

**Comment by PlayFriik** [comment]
It kills, because you were in creative.

**Comment by RebelLP** [comment]
no! https://www.youtube.com/watch?v=X04jAfmsti0&feature=youtu.be

**Comment by PlayFriik** [comment]
Oh, that's needed to tp you to your base. If it would just teleport you, then you can cheat by going into enemy's portal. It's not bug, it's intended as it is.

**Comment by RebelLP** [comment]
I've been rad if you did so to him for 1 teleported to their base after both clicks kit killed

**Comment by PlayFriik** [comment]
I just said that it's intended as it is. Otherwise people is going to abuse the teleport.

**Comment by RebelLP** [comment]
but I do not care about what's going on so people used the teleport with the other team, but I would love if you could Sending messages that bug and 2nd you avoid that he might steal things?

**Comment by PlayFriik** [comment]
Well, then you have to change it by yourself. I don't have time for every single people who want to change the plugin. I just keep it up-to-date.

**Comment by RebelLP** [comment]
much of it you please do it at least as he clicks on the kit so that da him to iventaře and you stare item of kit knockout

**Comment by PlayFriik** [comment]
God damn, abusers aren't going to click on the kit. They just want to get into their base. But killing is balancing it, because then they lose their stuff.

**Comment by RebelLP** [comment]
aha ok: /

**Comment by RebelLP** [comment]
Can you please send files, what should I import to eclipse it just does not work

**Comment by RebelLP** [comment]
NECHELA would you at least for me to do one plugin "Quest Shep" plugin would be used for the project
https://www.facebook.com/funnylandczech?fref=ts

**Comment by PlayFriik** [comment]
I did that already - https://www.spigotmc.org/resources/sheepquest-like-mineplex-bungeecord-1-8-0-1-8-7.8302/

**Comment by RebelLP** [comment]
xD for € 10? Is this a joke? I have no money! :(

**Comment by PlayFriik** [comment]
If you don't have money then that doesn't mean that my plugin is a joke.
Developing a plugin like that isn't that easy.

**Comment by RebelLP** [comment]
Yes, I know sam We tried to plugin development but I simply can not and will not me! I would love the pluginkoupil tim I'm also like to support the development of other plugin but I really have not got! :(

**Comment by PlayFriik** [comment]
Then you just can't get it.

**Comment by RebelLP** [comment]
Yes, I know :( :( would have wanted us to give it as a gift? :(

**Comment by PlayFriik** [comment]
No, other's have paid for it already, it's just unfair for them.
And your server should have budget where to start.

**Comment by RebelLP** [comment]
yes it is but I will tell you no budget or have no money :( and servers hosting valid :( it was not necessary that we have b given as a gift to the beginning know that it is not unjust to them but to me from you that we need help then we can advertise your plugins maybe he was in them an interest

**Comment by RebelLP** [comment]
¨?

**Comment by PlayFriik** [comment]
What?

**Comment by RebelLP** [comment]
Could you give us the data as a plug-sponsored darek.Podle me people would not mind that you would give us a little help in the beginning :(

**Comment by PlayFriik** [comment]
No. I had alot of work on it and I don't give it away free.

**Comment by RebelLP** [comment]
oh I know what is the pig do such ashley plugin I'd love to have you bought this plugin but do not have the money to look like a guy who's gifted understand the power you please grant us this plugin

**Comment by PlayFriik** [comment]
If you don't have the money then you just can not get it.

**Comment by RebelLP** [comment]
hm ok :( I know sorry I bothered you :( I do not know how to plug mam data to server :(

**Comment by RebelLP** [comment]
[01:04:50] [Server thread/ERROR]: Could not load 'plugins\Annihilation.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:152) ~[bukkit.jar:git-Bukkit-d27e6d0]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [bukkit.jar:git-Bukkit-d27e6d0]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:288) [bukkit.jar:git-Bukkit-d27e6d0]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.<init>(CraftServer.java:250) [bukkit.jar:git-Bukkit-d27e6d0]
	at net.minecraft.server.v1_8_R3.PlayerList.<init>(PlayerList.java:69) [bukkit.jar:git-Bukkit-d27e6d0]
	at net.minecraft.server.v1_8_R3.DedicatedPlayerList.<init>(SourceFile:14) [bukkit.jar:git-Bukkit-d27e6d0]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:179) [bukkit.jar:git-Bukkit-d27e6d0]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:503) [bukkit.jar:git-Bukkit-d27e6d0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 9 more

**Comment by RebelLP** [comment]
?

**Comment by PlayFriik** [comment]
Did you change the plugin?

**Comment by RebelLP** [comment]
All are imported into eclipse, as I said, but it does not work I'll be glad to see if you could send me everything jset to the imported thank you

**Comment by PlayFriik** [comment]
Screenshot your eclipse.

**Comment by RebelLP** [comment]
There have also video :) https://www.youtube.com/watch?v=6pTHJUOQzmA&feature=youtu.be

**Comment by PlayFriik** [comment]
Show your plugin.yml file.

**Comment by RebelLP** [comment]
name: Annihilation
main: net.PlayFriik.Annihilation.Annihilation
authors: [coasterman10, stuntguy3000, PlayFriik]
softdepend: [Vault]
version: 1.5.1
commands:
  annihilation:
    description: Plugin commands for Annihilation
    aliases: anni
  team:
    description: Team command for Annihilation
    aliases: t
  vote:
    description: Places vote for a map
    aliases: v
  stats:
    description: Lists your stats
    aliases: s
  class:
    description: Selects your kit
    aliases: c
  blue:
    description: Join the Blue team!
  green:
    description: Join the Green team!
  yellow:
    description: Join the Yellow team!
  red:
    description: Join the Red team!
  distance:
    description: Gets distance to enemy nexuses
    aliases: [d, dis]
  map:
    description: Admin Map commands
    aliases: m

**Comment by PlayFriik** [comment]
post that to pastebin.com

**Comment by RebelLP** [comment]
http://pastebin.com/RZswj4fz

**Comment by PlayFriik** [comment]
Also what errors(4) did you have on the project?

**Comment by RebelLP** [comment]
I guess I do not understand: /

**Comment by PlayFriik** [comment]
Then I can't help you.

**Comment by RebelLP** [comment]
I beg you to send me what you see if you have imported into eclipse after te nepude then you'll see how he

**Comment by PlayFriik** [comment]
I don't have it on my computer... I reinstalled my Windows operating system.

**Comment by RebelLP** [comment]
aha: / it's too bad because they are in the eclipse does not release so he's out of odstarnim to show the "mistakes"

**Comment by RebelLP** [comment]
Would you created for me 1 plugin for free? It would be a plugin who's on Minplexu.

**Comment by PlayFriik** [comment]
No, I don't have time for free plugins, I am working on my plugins what I get paid for.

**Comment by RebelLP** [comment]
Dobry den, was bych Jsem rad Kdyby jste mi Mohl dat jeste TENTO plugin dělat java souboru. sliuju Už to je posledni https://github.com/MCTyler/CrafterNexus
